# Generated by Django 4.0.2 on 2022-06-02 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_user_watchlist_card_last_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='last_review',
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
