# Generated by Django 4.0.2 on 2022-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_card_created_alter_card_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imdbRating',
            field=models.CharField(blank=True, default='N/A', max_length=8),
        ),
    ]
