# Generated by Django 4.0.2 on 2022-06-02 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_card_imdbrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='datetime',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='datetime',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
