# Generated by Django 4.0.2 on 2022-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_rename_datetime_item_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='modified',
            field=models.DateTimeField(default=None),
        ),
    ]
