# Generated by Django 4.0.2 on 2022-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_card_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='modified',
            field=models.DateTimeField(verbose_name='last_reviewed'),
        ),
    ]
