# Generated by Django 4.0.2 on 2022-06-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_alter_card_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
