# Generated by Django 4.0.2 on 2022-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='img',
            new_name='image',
        ),
    ]
