# Generated by Django 4.0.2 on 2022-06-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_rename_img_card_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imdb_id',
            new_name='id',
        ),
    ]
