# Generated by Django 4.0.2 on 2022-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_rename_imdb_id_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
