# Generated by Django 4.0.2 on 2022-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
